api-settings:
  port: 21960
  token: "zipcord"
  token-enabled: true
  link:
    database-name: "bins"
    enabled: true

default-world: "world"

forecast-words:
  time:
    day: "day" # Default word for day-time
    night: "night" # Default word for nighttime
    # Specific time words
    sunrise: "sunrise"
    morning: "morning"
    noon: "noon"
    afternoon: "afternoon"
    evening: "evening"
    sunset: "sunset"
    midnight: "midnight"
  weather:
    clear: "clear" # Default word for clear skies. This is also the word for night.
    sunny: "sunny" # Word for a clear day.
    rainy: "rainy"
    stormy: "stormy"